// Word Count : 155 \\

let words = 
[
	["notabilia", "matters, events, or items worthy of note."],
	["consider", "deem to be"],
	["minute","infinitely or immeasurably smal"],
	["accord","concurrence of opinion"],
	["evident","clearly revealed to the mind or the senses or judgmen"],
	["practice","a customary way of operation or behavior"],
	["intend","have in mind as a purpose"],
	["concern","something that interests you because it is important"],
	["commit","perform an act, usually with a negative connotation"],
	["issue","some situation or event that is thought about"],
	["approach","move towards"],
	["establish","set up or found"],	
	["utter","without qualification"],
	["conduct","direct the course of; manage or control"],
	["engage","consume all of one's attention or time"],
	["obtain","come into possession of"],
	["scarce","deficient in quantity or number compared with the demand"],
	["policy","a plan of action adopted by an individual or social group"],	
	["straight","successive, without a break"],
	["stock","capital raised by a corporation through the issue of shares"],
	["apparent","clearly revealed to the mind or the senses or judgment"],
	["property","a basic or essential attribute shared by members of a class"],
	["fancy","imagine; conceive of; see in one's mind"],
	["concept","an abstract or general idea inferred from specific instances"],
	["court","an assembly to conduct judicial business"],
	["appoint","assign a duty, responsibility or obligation to"],
	["passage","a section of text, particularly a section of medium length"],
	["vain","unproductive of success"],
	["instance","an occurrence of something"],
	["coast","the shore of a sea or ocean"],
	["project","a planned undertaking"],
	["commission","a special group delegated to consider some matter"],
	["constant","a quantity that does not vary"],
	["circumstances","one's overall condition in life"],
	["constitute","to compose or represent"],
	["level","a relative position or degree of value in a graded group"],
	["affect","have an influence upon"],
	["institute","set up or lay the groundwork for"],
	["render","give an interpretation of"],
	["appeal","be attractive to"],
	["generate","bring into existence"],
	["theory","a well-substantiated explanation of some aspect of the world"],
	["range","a variety of different things or activities"],
	["campaign","a race between candidates for elective office"],
	["league","an association of sports teams that organizes matches"],	
	["labor","any piece of work that is undertaken or attempted"],
	["confer","have a meeting in order to talk something over"],
	["grant","allow to have"],
	["dwell","think moodily or anxiously about something"],
	["entertain","provide amusement for"],
	["contract","a binding agreement that is enforceable by law"],	
	["earnest","characterized by a firm, humorless belief in one's opinions"],
	["yield","give or supply"],
	["wander","move or cause to move in a sinuous or circular course"],
	["insist","be emphatic or resolute and refuse to budge"],
	["knight","a person of noble birth trained to arms and chivalry"],
	["convince","make realize the truth or validity of something"],
	["inspire","serve as the inciting cause of"],
	["convention","a large formal assembly"],
	["skill","an ability that has been acquired by training"],
	["harry","annoy continually or chronically"],
	["financial","involving fiscal matters"],
	["reflect","show an image of"],
	["novel","an extended fictional work in prose"],
	["furnish","provide or equip with furniture"],
	["compel","force somebody to do something"],
	["venture","proceed somewhere despite the risk of possible dangers"],
	["territory","the geographical area under the jurisdiction of a state"],
	["temper","a characteristic state of feeling"],
	["context", "discourse that surrounds and helps explain a word or passage"],
	["bent", "fixed in your purpose"],
	["intimate", "marked by close acquaintance, association, or familiarity"],
	["undertake", "enter upon an activity or enterprise"],
	["majority", "more than half of the votes in an election"],
	["assert", "declare or affirm solemnly and formally as true"],
	["crew", "the men and women who man a vehicle"],
	["chamber", "a natural or artificial enclosed space"],
	["humble", "marked by meekness or modesty; not arrogant or prideful"],
	["scheme", "an elaborate and systematic plan of action"],
	["keen", "demonstrating ability to recognize or draw fine distinctions"],
	["liberal", "having political views favoring reform and progress"],
	["despair", "a state in which all hope is lost or absent"],
	["tide", "the periodic rise and fall of the sea level"],
	["attitude", "a complex mental state involving beliefs and feelings"],
	["justify", "show to be reasonable or provide adequate ground for"],
	["flag", "a rectangular piece of cloth of distinctive design"],
	["merit", "any admirable or beneficial attribute"],
	["manifest", "reveal its presence or make an appearance"],
	["notion", "a general inclusive concept"],
	["scale", "relative magnitude"],
	["formal", "characteristic of or befitting a person in authority"],
	["resource", "a new or reserve supply that can be drawn upon when needed"],
	["persist", "continue to exist"],
	["contempt", "lack of respect accompanied by a feeling of intense dislike"],
	["tour", "a route all the way around a particular place or area"],
	["plead", "enter a defendant's answer"],
	["weigh", "be oppressive or burdensome"],
	["mode", "how something is done or how it happens"],
	["distinction", "a discrimination between things as different"],
	["inclined", "at an angle to the horizontal or vertical position"],
	["attribute", "a quality belonging to or characteristic of an entity"],
	["exert", "make a great effort at a mental or physical task"],
	["oppress", "come down on or keep down by unjust use of one's authority"],
	["contend", "compete for something"],
	["stake", "a strong wooden or metal post driven into the ground"],
	["toil", "work hard"],
	["perish", "pass from physical life"],
	["disposition", "your usual mood"],
	["rail", "complain bitterly"],
	["cardinal", "one of a group of prominent bishops in the Sacred College"],
	["boast", "show off"],
	["advocate", "a person who pleads for a person, cause, or idea"],
	["bestow", "present"],
	["allege", "report or maintain"],
	["notwithstanding", "despite anything to the contrary"],
	["lofty", "of imposing height; especially standing out above others"],
	["multitude", "a large indefinite number"],
	["steep", "having a sharp inclination"],
	["heed", "pay close attention to"],
	["modest", "not large but sufficient in size or amount"],
	["partial", "being or affecting only a segment"],
	["apt", "naturally disposed toward"],
	["esteem", "the condition of being honored"],
	["credible", "appearing to merit belief or acceptance"],
	["provoke", "provide the needed stimulus for"],
	["tread", "a step in walking or running"],
	["ascertain", "learn or discover with confidence"],
	["fare", "proceed, get along, or succeed"],
	["cede", "relinquish possession or control over"],
	["perpetual", "continuing forever or indefinitely"],
	["decree", "a legally binding command or decision"],
	["contrive", "make or work out a plan for; devise"],
	["derived", "formed or developed from something else; not origina"],
	["elaborate", "marked by complexity and richness of detail"],
	["substantial", "real; having a material or factual existence"],
	["frontier", "a wilderness at the edge of a settled area of a country"],
	["facile", "arrived at without due care or effort; lacking depth"],
	["cite", "make reference to"],
	["warrant", "show to be reasonable or provide adequate ground for"],
	["sob", "weep convulsively"],
	["rider", "a traveler who actively sits and travels on an animal"],
	["dense", "permitting little if any light to pass through"],
	["afflict", "cause physical pain or suffering in"],
	["flourish", "grow vigorously"],
	["ordain", "invest with ministerial or priestly authority"],
	["pious", "having or showing or expressing reverence for a deity"],
	["vex", "disturb, especially by minor irritations"],
	["gravity", "the force of attraction between all masses in the universe"],
	["suspended", "supported or kept from sinking or falling by buoyancy"],
	["conspicuous", "obvious to the eye or mind"],
	["retort", "a quick reply to a question or remark"],
	["jet", "an airplane powered by gas turbines"],
	["bolt", "run away"],
	["assent", "to agree or express agreement"],
	["purse", "a sum spoken of as the contents of a money container"],
	["plus", "the arithmetic operation of summing"],
	["sanction", "give authority or permission to"],
];
